Handle class type parameters.
scalacenter/tasty-mima pull request #8
Opened 2022-12-16 17:10 UTC by sjrd

2022-12-16 19:03 UTC, bishabosha commented on tasty-mima/src/main/scala/tastymima/TypeTranslator.scala
> +          translatedPrefix.cls.typeParams(typeParamIndex)
what about index out of bounds?

2022-12-16 19:06 UTC, bishabosha requested changes
looks unsafe :)

2022-12-16 19:09 UTC, sjrd commented on tasty-mima/src/main/scala/tastymima/TypeTranslator.scala
> +          translatedPrefix.cls.typeParams(typeParamIndex)
Yes w that's something we should pre validate, because there is no reasonable fallback here.

2022-12-16 19:22 UTC, bishabosha commented on tasty-mima/src/main/scala/tastymima/TypeTranslator.scala
> +          translatedPrefix.cls.typeParams(typeParamIndex)
I guess put a comment?

2022-12-17 09:32 UTC, sjrd commented
I added a commit that properly checks class type argument count mismatch.

2022-12-17 12:58 UTC, bishabosha approved these changes

2022-12-17 12:58 UTC, merged